### ISSUE TITLE
almalinux: InvenioRDM step: RUN pipenv install --verbose --deploy --system fails

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/docker-invenio#75]
Package version (if known): registry.cern.ch/inveniosoftware/almalinux:1

## Describe the bug
When building our instance's image with `FROM registry.cern.ch/inveniosoftware/almalinux:1` (per https://github.com/inveniosoftware/cookiecutter-invenio-rdm/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/Dockerfile#L11), the image fails to build with a large error output that I truncated as follows:

```
 u''Step 4/12 : RUN pipenv install --deploy --system\n'', u'' ---> Running in dce117f57eeb\n'', u''\x1b[91m\x1b[0m'', u''Installing dependencies from Pipfile.lock (3ee068)...\n'', u"\x1b[91mAn
        error occurred while installing alembic==1.9.3 ; python_version >= ''3.7'' --hash=sha256:8fd6aaea56f5a703a190d25a705dfa91d7c313bb71de2f9c68f5abdcaf5df164 --hash=sha256:ed2f73ea9c986f43af8ad7502c5f60d6bb1400bcd6d29f230e760e08884cb476! Will try again.
        An error occurred while installing amqp==5.1.1 ; python_version >= ''3.6'' --hash=sha256:6f0956d2c23d8fa6e7691934d8c3930eadb44972cbbd1a7ae3a520f735d43359 --hash=sha256:2c1b13fecc0893e946c65cbd5f36427861cffa4ea2201d8f6fca22e2a373b5e2! Will try again.
        An error occurred while installing aniso8601==9.0.1 --hash=sha256:1d2b7ef82963909e93c4f24ce48d4de9e66009a21bf1c1e1c85bdd0812fe412f --hash=sha256:72e3117667eedf66951bb2d93f4296a56b94b078a8a95905a052611fb3f1b973! Will try again.
        An error occurred while installing appdirs==1.4.4 --hash=sha256:7d5d0167b2b1ba821647616af46a749d1c653740dd0d2415100fe26e27afdf41 --hash=sha256:a841dacd6b99318a741b166adb07e19ee71a274450e68237b4650ca1055ab128! Will try again.

[... this goes on for every dependency ...]

\x1b[0m", u''Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting alembic==1.9.3
[pipenv.exceptions.InstallError]:   Downloading alembic-1.9.3-py3-none-any.whl (210 kB)
[pipenv.exceptions.InstallError]: ERROR: Exception:
[pipenv.exceptions.InstallError]: Traceback (most recent call last):
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
[pipenv.exceptions.InstallError]:     status = run_func(*args)
\x1b[0m'', u''\x1b[91m[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/cli/req_command.py", line 247, in wrapper
[pipenv.exceptions.InstallError]:     return
    func(self, options, args)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/commands/install.py", line 400, in run
[pipenv.exceptions.InstallError]:     requirement_set = resolver.resolve(
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
[pipenv.exceptions.InstallError]:     result = self._result = resolver.resolve(
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
[pipenv.exceptions.InstallError]:     state = resolution.resolve(requirements, max_rounds=max_rounds)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
[pipenv.exceptions.InstallError]:     self._add_to_criteria(self.state.criteria, r, parent=None)
[pipenv.exceptions.InstallError]:   File
    "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
[pipenv.exceptions.InstallError]:     if not criterion.candidates:
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
[pipenv.exceptions.InstallError]:     return bool(self._sequence)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
[pipenv.exceptions.InstallError]:     return any(self)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
[pipenv.exceptions.InstallError]:     return (c for c in iterator if id(c) not in self._incompatible_ids)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py",
    line 47, in _iter_built
[pipenv.exceptions.InstallError]:     candidate = func()
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
[pipenv.exceptions.InstallError]:     self._link_candidate_cache[link] = LinkCandidate(
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 301, in __init__
[pipenv.exceptions.InstallError]:     super().__init__(
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 163, in __init__
[pipenv.exceptions.InstallError]:     self.dist = self._prepare()
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 232, in _prepare
[pipenv.exceptions.InstallError]:     dist
    = self._prepare_distribution()
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 312, in _prepare_distribution
[pipenv.exceptions.InstallError]:     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
[pipenv.exceptions.InstallError]:     return self._prepare_linked_requirement(req, parallel_builds)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
[pipenv.exceptions.InstallError]:     local_file = unpack_url(
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/operations/prepare.py", line 166, in unpack_url
[pipenv.exceptions.InstallError]:     file
    = get_http_url(
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/operations/prepare.py", line 107, in get_http_url
[pipenv.exceptions.InstallError]:     from_path, content_type = download(link, temp_dir.path)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/network/download.py", line 147, in __call__
[pipenv.exceptions.InstallError]:     for chunk in chunks:
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/cli/progress_bars.py", line 52, in _rich_progress_bar
[pipenv.exceptions.InstallError]:     with progress:
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/rich/progress.py", line 1165, in __enter__
[pipenv.exceptions.InstallError]:     self.start()
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/rich/progress.py",
    line 1156, in start
[pipenv.exceptions.InstallError]:     self.live.start(refresh=True)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/rich/live.py", line 132, in start
[pipenv.exceptions.InstallError]:     self._refresh_thread.start()
[pipenv.exceptions.InstallError]:   File "/usr/lib64/python3.9/threading.py", line 899, in start
[pipenv.exceptions.InstallError]:     _start_new_thread(self._bootstrap, ())
[pipenv.exceptions.InstallError]: RuntimeError: can\''t start new thread
```

## Steps to Reproduce
1. Try to run image build `FROM registry.cern.ch/inveniosoftware/almalinux:1`

## Expected behavior
That the image build like it used to (and does with `FROM inveniosoftware/centos7-python:3.9`).

**Comment by fenekku** [comment]
**Resolution**: a version of docker > 20.10 is needed to be able to run pipenv correctly during the build of an Almalinux image.

AlmaLinux (a distro picking up from where CentOS stable stopped) and most newer distros use new libc's `clone3()` call that is not supported by earlier docker versions. A version of docker greater than 20.10 is needed so that docker can take that change into account and not break when a new thread is created. We upgraded to 23.0.1 and don't observe the problem anymore.  
For more details see https://medium.com/nttlabs/ubuntu-21-10-and-fedora-35-do-not-work-on-docker-20-10-9-1cd439d9921 .
